#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.6
# from Racc grammer file "".
#

require 'racc/parser.rb'
module Fabulator
  module Grammar
    class Parser < Racc::Parser

module_eval(<<'...end regex.racc/module_eval...', 'regex.racc', 46)
  require 'fabulator/grammar'

  def parse(t, ctx)
    @source = t
    @curpos = 0 
    @context = ctx
    @line = 0   

    @yydebug = true
      
    @last_token = nil
  
    do_parse
  end
    
  def on_error(*args)
    raise Fabulator::Grammar::ParserError.new("unable to parse '#{args[1]}' near line #{@line + 1}, column #{@col}")
  end

  @@regex = {
    :ncname => %r{(?:[a-zA-Z_][-a-zA-Z0-9_.]*)}
  }

  @@regex[:qname] = %r{((?:#{@@regex[:ncname]}:)?#{@@regex[:ncname]})}

  def next_token
    @token = nil
    white_space = 0
    new_line = 0
    @col = 0
    while @curpos < @source.length && @source[@curpos..@curpos] =~ /\s/ do
      if @source[@curpos..@curpos] =~ /\n/
        new_line = new_line + 1
        @line = @line + 1
        @col = 0
      else
        @col = @col + 1
      end
      @curpos = @curpos + 1
      white_space = white_space + 1   
    end

    # skip comments delimited by (:  :)
    # comments can be nested
    # these are XPath 2.0 comments
    #
    if @curpos < @source.length && @source[@curpos..@curpos+1] == '(:'
      comment_depth = 1
      @curpos = @curpos + 2
      @col = @col + 2
      while comment_depth > 0 && @curpos < @source.length
        if @source[@curpos..@curpos+1] == '(:'
          comment_depth = comment_depth + 1
          @curpos = @curpos + 1
          @col = @col + 1
        end
        if @source[@curpos..@curpos+1] == ':)'
          comment_depth = comment_depth - 1
          @curpos = @curpos + 1
          @col = @col + 1
        end
        @curpos = @curpos + 1
        @col = @col + 1
      end
      white_space = white_space + 1
    end

    while @curpos < @source.length && @source[@curpos..@curpos] =~ /\s/ do
      if @source[@curpos..@curpos] =~ /\n/
        new_line = new_line + 1
        @line = @line + 1
        @col = 0
      else
        @col = @col + 1
      end
      @curpos = @curpos + 1
      white_space = white_space + 1
    end

    if @curpos >= @source.length
      @last_token = nil
      return [ false, false ]
    end

    case @source[@curpos..@curpos]
      when '<': @token = [ :LT, '<' ]
      when '>': @token = [ :GT, '>' ]
      when '[': @token = [ :LB, '[' ]
      when ']': @token = [ :RB, ']' ]
      when '(': @token = [ :LP, '(' ]
      when ')': @token = [ :RP, ')' ]
      when '{': @token = [ :LC, '{' ]
      when '}': @token = [ :RC, '}' ]
      when ':': @token = [ :COLON, ':' ]
      when ',': @token = [ :COMMA, ',' ]
      when '|': @token = [ :PIPE, '|' ]
      when '*': @token = [ :STAR, '*' ]
      when '+': @token = [ :PLUS, '+' ]
      when '.': @token = [ :DOT,  '.' ]
      when '?': @token = [ :QUESTION, '?' ]
      when '$': @token = [ :DOLLAR, '$' ]
      when '^': @token = [ :CARET, '^' ]
    end

    if @token.nil?
      # get longest sequence of non-special characters
      # if it's all digits, report INTEGER
      # if it's a qname, report QNAME
      # otherwise, report TEXT
      @source[@curpos..@source.length-1] =~ /^(((\\.)|[^ \$\^\[\]<>\{\}\(\):,|*+.?])+)*/
      text = $1
      bits = text.split(/\\/)
      text = bits.join('')
      @curpos += bits.size - 1
      if text.length > 0
        if @source[@curpos+text.length .. @curpos+text.length] =~ /[*?+\{]/
          text = text[0..text.length-2]
          @token = [ :TEXT, text ]
        else
          case text
            when /^\d+$/: @token = [ :INTEGER, text ]
            when /^#{@@regex[:ncname]}$/: @token = [ :NCNAME, text ]
            else @token = [ :TEXT, text ]
          end
        end
      end
    end

    if @token.nil?
      puts "Uh oh... we don't know what to do: #{@source[@curpos .. @source.length-1]}"
    else
      @curpos += @token[1].length
    end

    return @token
  end
...end regex.racc/module_eval...
##### State transition tables begin ###

racc_action_table = [
    30,    13,     5,    15,     6,    17,     6,     7,     8,     9,
    12,    13,    37,    15,    41,    17,    32,     7,     8,     9,
     9,    42,    22,    23,    25,    26,     7,     8,     9,    39,
    40,    21,    31,     4,    33,    34,    35,    36,     4,    38,
    19,     4,    43,    44,    45 ]

racc_action_check = [
    18,    18,     1,    18,     1,    18,    28,    18,    18,    18,
     3,     3,    28,     3,    40,     3,    22,     3,     3,     3,
    13,    40,    11,    11,    11,    11,    17,    17,    17,    35,
    35,     9,    21,    15,    23,    25,    26,    27,     6,    29,
     5,     0,    41,    42,    43 ]

racc_action_pointer = [
    38,     2,   nil,     6,   nil,    40,    35,   nil,   nil,    17,
   nil,     7,   nil,     7,   nil,    30,   nil,    15,    -4,   nil,
   nil,    19,     0,    18,   nil,    19,    24,    31,     4,    29,
   nil,   nil,   nil,   nil,   nil,    10,   nil,   nil,   nil,   nil,
     2,    23,    27,    28,   nil,   nil ]

racc_action_default = [
    -7,   -31,    -1,    -3,    -7,   -31,    -7,   -16,   -17,   -18,
    -8,   -10,    -5,   -31,   -15,    -7,   -12,   -31,    -4,    46,
    -2,   -31,   -20,   -24,    -9,   -22,   -31,   -31,   -31,   -31,
    -6,   -19,   -21,   -25,   -23,   -31,   -11,   -13,   -14,   -26,
   -31,   -31,   -28,   -27,   -29,   -30 ]

racc_goto_table = [
     1,    24,    18,    20,    27,    29,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    28 ]

racc_goto_check = [
     1,     6,     3,     2,     7,     8,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,     1 ]

racc_goto_pointer = [
   nil,     0,    -3,    -2,   nil,   nil,   -10,    -9,   -12 ]

racc_goto_default = [
   nil,   nil,     2,     3,    10,    11,   nil,    14,    16 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 22, :_reduce_1,
  3, 22, :_reduce_2,
  1, 23, :_reduce_3,
  2, 23, :_reduce_4,
  2, 23, :_reduce_5,
  3, 23, :_reduce_6,
  0, 24, :_reduce_7,
  2, 24, :_reduce_8,
  2, 25, :_reduce_9,
  1, 25, :_reduce_10,
  3, 26, :_reduce_11,
  1, 26, :_reduce_12,
  3, 26, :_reduce_13,
  3, 26, :_reduce_14,
  1, 29, :_reduce_15,
  1, 29, :_reduce_16,
  1, 29, :_reduce_17,
  1, 28, :_reduce_18,
  3, 28, :_reduce_19,
  1, 27, :_reduce_20,
  2, 27, :_reduce_21,
  1, 27, :_reduce_22,
  2, 27, :_reduce_23,
  1, 27, :_reduce_24,
  2, 27, :_reduce_25,
  3, 27, :_reduce_26,
  5, 27, :_reduce_27,
  4, 27, :_reduce_28,
  5, 27, :_reduce_29,
  6, 27, :_reduce_30 ]

racc_reduce_n = 31

racc_shift_n = 46

racc_token_table = {
  false => 0,
  :error => 1,
  :PIPE => 2,
  :CARET => 3,
  :DOLLAR => 4,
  :LT => 5,
  :GT => 6,
  :LP => 7,
  :RP => 8,
  :LB => 9,
  :RB => 10,
  :TEXT => 11,
  :INTEGER => 12,
  :NCNAME => 13,
  :COLON => 14,
  :STAR => 15,
  :QUESTION => 16,
  :PLUS => 17,
  :LC => 18,
  :RC => 19,
  :COMMA => 20 }

racc_nt_base = 21

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "PIPE",
  "CARET",
  "DOLLAR",
  "LT",
  "GT",
  "LP",
  "RP",
  "LB",
  "RB",
  "TEXT",
  "INTEGER",
  "NCNAME",
  "COLON",
  "STAR",
  "QUESTION",
  "PLUS",
  "LC",
  "RC",
  "COMMA",
  "$start",
  "rules",
  "anchored_rule",
  "rule",
  "sequence",
  "sub_sequence",
  "sequence_qualifiers",
  "qname",
  "text" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'regex.racc', 5)
  def _reduce_1(val, _values, result)
     result = Fabulator::Grammar::Expr::Rules.new; result.add_alternative(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'regex.racc', 6)
  def _reduce_2(val, _values, result)
     result = val[0]; result.add_alternative(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'regex.racc', 8)
  def _reduce_3(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'regex.racc', 9)
  def _reduce_4(val, _values, result)
     result = val[1]; result.anchor_start 
    result
  end
.,.,

module_eval(<<'.,.,', 'regex.racc', 10)
  def _reduce_5(val, _values, result)
     result = val[0]; result.anchor_end 
    result
  end
.,.,

module_eval(<<'.,.,', 'regex.racc', 11)
  def _reduce_6(val, _values, result)
     result = val[1]; result.anchor_start; result.anchor_end 
    result
  end
.,.,

module_eval(<<'.,.,', 'regex.racc', 13)
  def _reduce_7(val, _values, result)
     result = Fabulator::Grammar::Expr::Rule.new; 
    result
  end
.,.,

module_eval(<<'.,.,', 'regex.racc', 14)
  def _reduce_8(val, _values, result)
     result = val[0]; result.add_sequence(val[1]); 
    result
  end
.,.,

module_eval(<<'.,.,', 'regex.racc', 16)
  def _reduce_9(val, _values, result)
     result = Fabulator::Grammar::Expr::Sequence.new(val[0], val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'regex.racc', 17)
  def _reduce_10(val, _values, result)
     result = Fabulator::Grammar::Expr::Sequence.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'regex.racc', 19)
  def _reduce_11(val, _values, result)
     result = Fabulator::Grammar::Expr::RuleRef.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'regex.racc', 20)
  def _reduce_12(val, _values, result)
     result = Fabulator::Grammar::Expr::Text.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'regex.racc', 21)
  def _reduce_13(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'regex.racc', 22)
  def _reduce_14(val, _values, result)
     result = Fabulator::Grammar::Expr::CharSet.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'regex.racc', 24)
  def _reduce_15(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'regex.racc', 25)
  def _reduce_16(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'regex.racc', 26)
  def _reduce_17(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'regex.racc', 28)
  def _reduce_18(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'regex.racc', 29)
  def _reduce_19(val, _values, result)
     result = val[0] + ':' + val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'regex.racc', 31)
  def _reduce_20(val, _values, result)
     result = [ :zero_or_more ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'regex.racc', 32)
  def _reduce_21(val, _values, result)
     result = [ :zero_or_more, :min ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'regex.racc', 33)
  def _reduce_22(val, _values, result)
     result = [ :one_or_more ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'regex.racc', 34)
  def _reduce_23(val, _values, result)
     result = [ :one_or_more, :min ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'regex.racc', 35)
  def _reduce_24(val, _values, result)
     result = [ :zero_or_one ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'regex.racc', 36)
  def _reduce_25(val, _values, result)
     result = [ :zero_or_one, :min ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'regex.racc', 37)
  def _reduce_26(val, _values, result)
     result = [ :exact, val[1].to_i ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'regex.racc', 38)
  def _reduce_27(val, _values, result)
     result = [ :range, val[1].to_i, val[3].to_i ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'regex.racc', 39)
  def _reduce_28(val, _values, result)
     result = [ :range, val[1], '' ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'regex.racc', 40)
  def _reduce_29(val, _values, result)
     result = [ :min, :range, val[1], '' ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'regex.racc', 41)
  def _reduce_30(val, _values, result)
     result = [ :min, :range, val[1].to_i, val[3].to_i ] 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

    end   # class Parser
    end   # module Grammar
  end   # module Fabulator
