#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.6
# from Racc grammer file "".
#

require 'racc/parser.rb'
module Fabulator
  module Grammar
    class RuleParser < Racc::Parser

module_eval(<<'...end rules.racc/module_eval...', 'rules.racc', 58)
  require 'fabulator/grammar'

  def parse(t)
    @source = t
    @curpos = 0
    @line = 0
    @col = 0

    @in_quantifier = false
       
    @yydebug = true

    @last_token = nil
       
    do_parse
  end

  def on_error(*args)
    raise Fabulator::Grammar::ParserError.new("unable to parse '#{args[1]}' near line #{@line + 1}, column #{@col}")
  end

  @@ops = {
    ':=' => :COLON_EQUAL,
    '['  => :LB,
    ']'  => :RB,
    '('  => :LP,
    ')'  => :RP,
    '{'  => :LC,
    '}'  => :RC,
    '?'  => :QUESTION,
    '.'  => :DOT,
    '..' => :DOT_DOT,
    '...'=> :DOT_DOT_DOT,
    '...!'=> :DOT_DOT_DOT_BANG,
    '|'  => :PIPE,
    ','  => :COMMA,
    ':'  => :COLON
  }

  @@regex = {
    :simple_tokens => %r{^(#{Regexp.union(@@ops.keys.sort_by{|a| a.length}.reverse.collect{ |k| k })})},
    :ncname => %r{(?:[a-zA-Z_][-a-zA-Z0-9_.]*)},
    :integer => %r{(\d+)},
    :literal => %r{((?:"(?:[^\\"]*(?:\\.[^\\"]*)*)")|(?:'(?:[^\\']*(?:\\.[^\\']*)*)'))},
  }

  @@regex[:general] = Regexp.compile(%{^(#{@@regex[:ncname]})|#{@@regex[:integer]}|#{@@regex[:literal]}})

  def next_token
    @token = nil  
    white_space = 0
    new_line = 0
    while @curpos < @source.length && @source[@curpos..@curpos] =~ /\s/ do
      if @source[@curpos..@curpos] =~ /\n/
        new_line = new_line + 1
        @line = @line + 1
        @col = 0
      else
        @col = @col + 1
      end   
      @curpos = @curpos + 1
      white_space = white_space + 1
    end
    
    # skip comments delimited by (:  :)
    # comments can be nested
    # these are XPath 2.0 comments
    #

    if @curpos < @source.length && @source[@curpos..@curpos+1] == '(:'
      comment_depth = 1
      @curpos = @curpos + 2
      @col = @col + 2
      while comment_depth > 0 && @curpos < @source.length
        if @source[@curpos..@curpos+1] == '(:'
          comment_depth = comment_depth + 1
          @curpos = @curpos + 1
          @col = @col + 1
        end
        if @source[@curpos..@curpos+1] == ':)'
          comment_depth = comment_depth - 1
          @curpos = @curpos + 1
          @col = @col + 1
        end
        @curpos = @curpos + 1
        @col = @col + 1
      end
      white_space = white_space + 1
    end
    
    while @curpos < @source.length && @source[@curpos..@curpos] =~ /\s/ do
      if @source[@curpos..@curpos] =~ /\n/
        new_line = new_line + 1
        @line = @line + 1
        @col = 0
      else
        @col = @col + 1
      end   
      @curpos = @curpos + 1
      white_space = white_space + 1
    end
    
    if @curpos >= @source.length
      @last_token = nil
      return [ false, false ]
    end

    res = @@regex[:simple_tokens].match(@source[@curpos..@source.length-1])
    if !res.nil?
      if !res[1].nil?  
        @token = [ @@ops[res[1]], res[1] ]
      end
    end
  
    if @token.nil?
      res = @@regex[:general].match(@source[@curpos..@source.length-1])
      if res.nil?
        raise "Failed to parse '#{@source}' at #{@curpos}': #{@source[@curpos..@source.length-1]}"
      end
  #ncname, integer, literal
      if !res[1].nil?
        @token = [:NCNAME, res[1].to_s]
      elsif !res[2].nil?
        @token = [:INTEGER, res[2].to_s]
      elsif !res[3].nil?
        @token = [:LITERAL, res[3].to_s]
        @token[1] = @token[1][1..@token[1].size-2]
        @col += 2
        @curpos += 2
      end
    end


    if @token.nil?
      puts "Uh oh... we don't know what to do: #{@source[@curpos .. @source.length-1]}"
      return [ nil, nil ]
    else
      @curpos += @token[1].length
      @col += @token[1].length
    end

    if !@token.nil? && @token[0] == :LP
       # shorthand: if we see '(s[ )]', '(s?[ )]', '(?)', '(\d', then we have
       if @curpos > 1 && ![' ', '('].include?(@source[@curpos-2 .. @curpos-2])
         @token[0] = :LLP
         @in_quantifier = true
       end
    elsif @in_quantifier
      @in_quantifier = false
      if @token[0] == :NCNAME
        @token[0] = case @token[1]
          when 's': :S
          else :NCNAME
        end
      end
    end

    if @token[0] == :LB
      @in_directive = true
    elsif @in_directive && @token[0] == :NCNAME
      @token[0] = @token[1].upcase.to_sym
      @in_directive = false
    end

  #  puts "token: #{@token.join(' => ')}"
    return @token
  end
...end rules.racc/module_eval...
##### State transition tables begin ###

racc_action_table = [
    10,    11,    42,    13,    10,    11,     4,    13,    43,    21,
     8,     9,    21,    41,     8,     9,    11,    48,    11,     5,
     6,    21,    35,     5,     6,    60,    21,     5,     6,    21,
     5,     6,    21,    49,     5,     6,     5,     6,    21,     5,
     6,    21,    50,    37,     5,     6,    54,     5,     6,    21,
     5,     6,     3,    34,     4,    10,     5,     6,    13,     5,
     6,    55,    51,    34,    57,     8,     9,     5,     6,    29,
    58,    30,    31,    27,    28,    44,    26,    45,    46,    47,
    25,    62,    63,    18,    65,    66 ]

racc_action_check = [
     2,     2,    30,     2,    19,    19,    20,    19,    31,    54,
     2,     2,     7,    29,    19,    19,     8,    38,     9,     2,
     2,    55,    20,    19,    19,    54,    60,    54,    54,    46,
     7,     7,    28,    40,     8,     8,     9,     9,    51,    55,
    55,    27,    44,    25,    60,    60,    46,    46,    46,    45,
    28,    28,     1,    22,     1,    14,    51,    51,    14,    27,
    27,    47,    45,    17,    52,    14,    14,    45,    45,    13,
    53,    13,    13,    13,    13,    34,    11,    34,    34,    34,
    10,    56,    59,     3,    61,    64 ]

racc_action_pointer = [
   nil,    52,    -3,    83,   nil,   nil,   nil,     8,    12,    14,
    76,    61,   nil,    62,    52,   nil,   nil,    47,   nil,     1,
     4,   nil,    37,   nil,   nil,    38,   nil,    37,    28,     5,
    -6,     0,   nil,   nil,    58,   nil,   nil,   nil,     9,   nil,
    25,   nil,   nil,   nil,    24,    45,    25,    41,   nil,   nil,
   nil,    34,    46,    52,     5,    17,    63,   nil,   nil,    64,
    22,    66,   nil,   nil,    67,   nil,   nil ]

racc_action_default = [
    -3,   -34,    -1,   -34,    -3,   -31,    -3,   -34,   -34,   -34,
   -34,   -33,    -4,   -34,    -5,    -6,    -7,   -18,    67,    -2,
   -34,   -33,   -20,   -15,   -16,   -34,   -21,   -29,   -29,   -34,
   -34,   -34,    -8,   -17,   -34,   -32,   -19,    -9,   -34,   -30,
   -34,   -10,   -11,   -12,   -34,   -29,   -29,   -34,   -13,   -14,
   -22,   -29,   -34,   -34,   -29,   -29,   -34,   -23,   -25,   -34,
   -29,   -34,   -24,   -28,   -34,   -27,   -26 ]

racc_goto_table = [
    38,    40,    33,    17,    19,     1,    32,    36,    22,    17,
    17,    20,    23,    24,   nil,   nil,   nil,   nil,    52,    53,
    17,   nil,   nil,   nil,    56,   nil,   nil,    59,    61,   nil,
   nil,   nil,   nil,    64 ]

racc_goto_check = [
     7,     7,     9,     8,     2,     1,     6,     9,     8,     8,
     8,     1,     5,     5,   nil,   nil,   nil,   nil,     7,     7,
     8,   nil,   nil,   nil,     7,   nil,   nil,     7,     7,   nil,
   nil,   nil,   nil,     7 ]

racc_goto_pointer = [
   nil,     5,     0,   nil,   nil,     4,    -8,   -27,     1,   -15,
   nil ]

racc_goto_default = [
   nil,   nil,     2,    12,    14,    15,    16,   nil,    39,   nil,
     7 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 25, :_reduce_1,
  3, 25, :_reduce_2,
  0, 26, :_reduce_3,
  2, 26, :_reduce_4,
  1, 27, :_reduce_none,
  1, 27, :_reduce_none,
  1, 28, :_reduce_7,
  2, 28, :_reduce_8,
  3, 30, :_reduce_9,
  3, 30, :_reduce_none,
  3, 30, :_reduce_none,
  3, 30, :_reduce_none,
  4, 30, :_reduce_13,
  4, 30, :_reduce_14,
  2, 30, :_reduce_15,
  2, 30, :_reduce_16,
  2, 29, :_reduce_17,
  1, 29, :_reduce_18,
  3, 29, :_reduce_19,
  2, 29, :_reduce_20,
  2, 34, :_reduce_21,
  3, 33, :_reduce_22,
  4, 33, :_reduce_23,
  5, 33, :_reduce_24,
  4, 33, :_reduce_25,
  6, 33, :_reduce_26,
  5, 33, :_reduce_27,
  5, 33, :_reduce_28,
  0, 31, :_reduce_none,
  1, 31, :_reduce_none,
  1, 32, :_reduce_31,
  3, 32, :_reduce_32,
  1, 32, :_reduce_33 ]

racc_reduce_n = 34

racc_shift_n = 67

racc_token_table = {
  false => 0,
  :error => 1,
  :PIPE => 2,
  :LC => 3,
  :NCNAME => 4,
  :RC => 5,
  :LB => 6,
  :COMMIT => 7,
  :RB => 8,
  :UNCOMMIT => 9,
  :REJECT => 10,
  :SKIP => 11,
  :RESYNC => 12,
  :DOT_DOT_DOT => 13,
  :DOT_DOT_DOT_BANG => 14,
  :COLON_EQUAL => 15,
  :LLP => 16,
  :QUESTION => 17,
  :RP => 18,
  :S => 19,
  :INTEGER => 20,
  :DOT_DOT => 21,
  :LITERAL => 22,
  :LP => 23 }

racc_nt_base = 24

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "PIPE",
  "LC",
  "NCNAME",
  "RC",
  "LB",
  "COMMIT",
  "RB",
  "UNCOMMIT",
  "REJECT",
  "SKIP",
  "RESYNC",
  "DOT_DOT_DOT",
  "DOT_DOT_DOT_BANG",
  "COLON_EQUAL",
  "LLP",
  "QUESTION",
  "RP",
  "S",
  "INTEGER",
  "DOT_DOT",
  "LITERAL",
  "LP",
  "$start",
  "rules",
  "rule",
  "rule_bit",
  "directives",
  "sequence",
  "directive",
  "opt_separator",
  "atom",
  "sequence_qualifiers",
  "hypothetical" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'rules.racc', 6)
  def _reduce_1(val, _values, result)
     result = Fabulator::Grammar::Expr::Rule.new; result.add_alternative(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'rules.racc', 7)
  def _reduce_2(val, _values, result)
     result = val[0]; result.add_alternative(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'rules.racc', 9)
  def _reduce_3(val, _values, result)
     result = Fabulator::Grammar::Expr::RuleAlternative.new; 
    result
  end
.,.,

module_eval(<<'.,.,', 'rules.racc', 10)
  def _reduce_4(val, _values, result)
     result = val[0]; result.add_sequence(val[1]) 
    result
  end
.,.,

# reduce 5 omitted

# reduce 6 omitted

module_eval(<<'.,.,', 'rules.racc', 15)
  def _reduce_7(val, _values, result)
     result = [ val[0] ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'rules.racc', 16)
  def _reduce_8(val, _values, result)
     result = val[0] + [ val[1] ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'rules.racc', 18)
  def _reduce_9(val, _values, result)
     result = Fabulator::Grammar::Expr::RuleMode.new(val[1]) 
    result
  end
.,.,

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

module_eval(<<'.,.,', 'rules.racc', 22)
  def _reduce_13(val, _values, result)
     result = Fabulator::Grammar::Expr::SetSkip.new(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'rules.racc', 23)
  def _reduce_14(val, _values, result)
     result = Fabulator::Grammar::Expr::Resync.new(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'rules.racc', 24)
  def _reduce_15(val, _values, result)
     result = Fabulator::Grammar::Expr::LookAhead.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'rules.racc', 25)
  def _reduce_16(val, _values, result)
     result = Fabulator::Grammar::Expr::NegLookAhead.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'rules.racc', 27)
  def _reduce_17(val, _values, result)
     result = Fabulator::Grammar::Expr::RuleSequence.new(nil, val[0], val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'rules.racc', 28)
  def _reduce_18(val, _values, result)
     result = Fabulator::Grammar::Expr::RuleSequence.new(nil, val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'rules.racc', 29)
  def _reduce_19(val, _values, result)
     result = Fabulator::Grammar::Expr::RuleSequence.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'rules.racc', 30)
  def _reduce_20(val, _values, result)
     result = Fabulator::Grammar::Expr::RuleSequence.new(val[0], val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'rules.racc', 32)
  def _reduce_21(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'rules.racc', 40)
  def _reduce_22(val, _values, result)
     result = [ '?' ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'rules.racc', 41)
  def _reduce_23(val, _values, result)
     result = [ 's', val[2] ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'rules.racc', 42)
  def _reduce_24(val, _values, result)
     result = [ 's?', val[3] ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'rules.racc', 43)
  def _reduce_25(val, _values, result)
     result = [ 'count', val[1], val[2] ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'rules.racc', 44)
  def _reduce_26(val, _values, result)
     result = [ 'range', [ val[1], val[3] ], val[4] ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'rules.racc', 45)
  def _reduce_27(val, _values, result)
     result = [ 'upto', val[2], val[3] ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'rules.racc', 46)
  def _reduce_28(val, _values, result)
     result = [ 'atleast', val[1],val[3] ] 
    result
  end
.,.,

# reduce 29 omitted

# reduce 30 omitted

module_eval(<<'.,.,', 'rules.racc', 51)
  def _reduce_31(val, _values, result)
     result = Fabulator::Grammar::Expr::Text.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'rules.racc', 52)
  def _reduce_32(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'rules.racc', 53)
  def _reduce_33(val, _values, result)
     result = Fabulator::Grammar::Expr::RuleRef.new(val[0]) 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

    end   # class RuleParser
    end   # module Grammar
  end   # module Fabulator
