#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.6
# from Racc grammer file "".
#

require 'racc/parser.rb'
module Fabulator
  module Grammar
    class TokenParser < Racc::Parser

module_eval(<<'...end tokens.racc/module_eval...', 'tokens.racc', 70)
  require 'fabulator/grammar'

  def parse(t)
    @source = t
    @curpos = 0 
    @col = 0
    @line = 0   

    @yydebug = true
      
    @last_token = nil

    @brackets = 0
  
    do_parse
  end
    
  def on_error(*args)
    raise Fabulator::Grammar::ParserError.new("unable to parse '#{args[1]}' near line #{@line + 1}, column #{@col}")
  end

  @@ops = {
    #'[{' => :LB_LC,
    #'}]' => :RC_RB,
    #'[[' => :LB_LB,
    #']]' => :RB_RB,
    '['  => :LB,
    ']'  => :RB,
    '('  => :LP,
    ')'  => :RP,
    #'{'  => :LC,
    #'}'  => :RC,
    #'#'  => :HASH,
    '$'  => :DOLLAR,
    '^'  => :CARET,
    #'&'  => :AND,
    '*'  => :STAR,
    '+'  => :PLUS,
    '-'  => :MINUS,
    '?'  => :QUESTION,
    '.'  => :DOT,
    '|'  => :PIPE,
    ','  => :COMMA,
    ':'  => :COLON
  }


  @@regex = {
     :simple_tokens => %r{^(#{Regexp.union(@@ops.keys.sort_by{|a| a.length}.reverse.collect{ |k| k })})},
    :ncname => %r{(?:[a-zA-Z_][-a-zA-Z0-9_.]*)}
  }

 #puts @@regex[:simple_tokens]

  @@regex[:qname] = %r{((?:#{@@regex[:ncname]}:)?#{@@regex[:ncname]})}
  @@regex[:general] = Regexp.compile(%{^#{@@regex[:qname]}|#{@@regex[:simple_tokens]}})

  def next_token
    @token = nil
    white_space = 0
    new_line = 0
    while @curpos < @source.length && @source[@curpos..@curpos] =~ /\s/ do
      if @source[@curpos..@curpos] =~ /\n/
        new_line = new_line + 1
        @line = @line + 1
        @col = 0
      else
        @col = @col + 1
      end
      @curpos = @curpos + 1
      white_space = white_space + 1   
    end

    # skip comments delimited by (:  :)
    # comments can be nested
    # these are XPath 2.0 comments
    #
    if @curpos < @source.length && @source[@curpos..@curpos+1] == '(:'
      comment_depth = 1
      @curpos = @curpos + 2
      @col = @col + 2
      while comment_depth > 0 && @curpos < @source.length
        if @source[@curpos..@curpos+1] == '(:'
          comment_depth = comment_depth + 1
          @curpos = @curpos + 1
          @col = @col + 1
        end
        if @source[@curpos..@curpos+1] == ':)'
          comment_depth = comment_depth - 1
          @curpos = @curpos + 1
          @col = @col + 1
        end
        @curpos = @curpos + 1
        @col = @col + 1
      end
      white_space = white_space + 1
    end

    while @curpos < @source.length && @source[@curpos..@curpos] =~ /\s/ do
      if @source[@curpos..@curpos] =~ /\n/
        new_line = new_line + 1
        @line = @line + 1
        @col = 0
      else
        @col = @col + 1
      end
      @curpos = @curpos + 1
      white_space = white_space + 1
    end

    if @curpos >= @source.length
      @last_token = nil
      return [ false, false ]
    end

#    case @source[@curpos..@curpos]
#      when '<': @token = [ :LT, '<' ]
#      when '>': @token = [ :GT, '>' ]
#      when '[': @token = [ :LB, '[' ]
#      when ']': @token = [ :RB, ']' ]
#      when '(': @token = [ :LP, '(' ]
#      when ')': @token = [ :RP, ')' ]
#      when '{': @token = [ :LC, '{' ]
#      when '}': @token = [ :RC, '}' ]
#      when ':': @token = [ :COLON, ':' ]
#      when ',': @token = [ :COMMA, ',' ]
#      when '|': @token = [ :PIPE, '|' ]
#      when '*': @token = [ :STAR, '*' ]
#      when '+': @token = [ :PLUS, '+' ]
#      when '.': @token = [ :DOT,  '.' ]
#      when '?': @token = [ :QUESTION, '?' ]
#      when '$': @token = [ :DOLLAR, '$' ]
#      when '^': @token = [ :CARET, '^' ]
#    end

    res = @@regex[:simple_tokens].match(@source[@curpos..@source.length-1])
    if !res.nil?
      if !res[1].nil?
        @token = [ @@ops[res[1]], res[1] ]
      end
    end

    if @token.nil?
      # get longest sequence of non-special characters
      # if it's all digits, report INTEGER
      # if it's a qname, report QNAME
      # otherwise, report TEXT
      @source[@curpos..@source.length-1] =~ /^(((\\.)|[^ \$\^\[\]\{\}\(\):,|*+.?])+)*/
      text = $1
      bits = text.split(/\\/)
      text = bits.join('')
      @curpos += bits.size - 1
      @col += bits.size - 1
      if text.length > 0
        if @source[@curpos+text.length .. @curpos+text.length] =~ /[*?+\{]/
# TODO: make sure we backtrack properly if the last character is escaped
          text = text[0..text.length-2]
          @token = [ :TEXT, text ]
        else
          case text
            when /^\d+$/: @token = [ :INTEGER, text ]
            when /^#{@@regex[:ncname]}$/: @token = [ :NCNAME, text ]
            else @token = [ :TEXT, text ]
          end
        end
      end
    end

    if @token.nil?
      puts "Uh oh... we don't know what to do: #{@source[@curpos .. @source.length-1]}"
    else
      @curpos += @token[1].length
      @col += @token[1].length
    end

    if @token[0] == :LB
      if @brackets == 0 && @source[@curpos..@source.length-1] =~ /^\s*\d/
        @token[0] = :LLB
      end
      @brackets += 1
    elsif @token[0] == :RB
      @brackets -= 1
    elsif @brackets > 1
      @token[0] = :CHAR_TEXT
    end

    return @token
  end
...end tokens.racc/module_eval...
##### State transition tables begin ###

racc_action_table = [
    11,    14,    17,     6,    19,     7,    11,    14,    17,     8,
    19,    10,    13,    16,    28,     8,    55,    10,    13,    16,
    65,    29,    31,    32,    54,     7,    35,    64,    36,    35,
    42,    36,    34,    46,    35,    34,    36,    35,    45,    36,
    34,    38,    35,    34,    36,    44,    38,    47,    34,    60,
    61,    58,    57,    43,    59,    53,    52,    53,    52,    50,
    41,     4,    26,    56,    25,     4,    23,    21,     4,    66,
    67,    68,    69,    70 ]

racc_action_check = [
    22,    22,    22,     1,    22,     1,     3,     3,     3,    22,
     3,    22,    22,    22,    18,     3,    46,     3,     3,     3,
    54,    18,    18,    18,    46,    27,    52,    54,    52,    38,
    27,    38,    52,    32,    53,    38,    53,    19,    31,    19,
    53,    19,    35,    19,    35,    29,    35,    34,    35,    49,
    49,    49,    48,    28,    49,    48,    48,    39,    39,    37,
    25,    17,    11,    47,     8,     7,     6,     4,     0,    58,
    61,    64,    65,    68 ]

racc_action_pointer = [
    65,     3,   nil,     2,    64,   nil,    66,    62,    52,   nil,
   nil,    58,   nil,   nil,   nil,   nil,   nil,    58,     3,    31,
   nil,   nil,    -4,   nil,   nil,    47,   nil,    23,    34,    26,
   nil,    19,    17,   nil,    34,    36,   nil,    50,    23,    47,
   nil,   nil,   nil,   nil,   nil,   nil,     7,    51,    45,    40,
   nil,   nil,    20,    28,    11,   nil,   nil,   nil,    55,   nil,
   nil,    56,   nil,   nil,    62,    53,   nil,   nil,    54,   nil,
   nil ]

racc_action_default = [
   -11,   -48,    -1,    -3,    -7,   -11,   -48,   -11,   -35,   -31,
   -32,    -9,    -5,   -33,   -16,   -12,   -34,   -11,   -14,   -48,
   -15,    -8,    -4,    71,    -2,   -48,   -10,   -48,   -39,   -37,
   -13,   -41,   -48,   -20,   -48,   -48,   -27,   -48,   -48,   -19,
    -6,   -36,   -17,   -40,   -38,   -42,   -48,   -48,   -48,   -48,
   -18,   -21,   -48,   -48,   -48,   -43,   -25,   -26,   -48,   -28,
   -24,   -48,   -22,   -23,   -48,   -45,   -30,   -29,   -44,   -46,
   -47 ]

racc_goto_table = [
    12,     1,    51,    30,    39,    37,    22,    24,    49,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    62,    63,    27,    40,
    48 ]

racc_goto_check = [
     5,     1,    12,     8,    11,    10,     3,     2,    13,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    12,    12,     1,     5,
    11 ]

racc_goto_pointer = [
   nil,     1,     0,     1,   nil,    -3,   nil,   nil,   -15,   nil,
   -14,   -15,   -36,   -28,   nil ]

racc_goto_default = [
   nil,   nil,     2,     3,     5,   nil,    15,    18,   nil,    20,
   nil,   nil,    33,   nil,     9 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 22, :_reduce_1,
  3, 22, :_reduce_2,
  1, 23, :_reduce_3,
  2, 23, :_reduce_4,
  2, 23, :_reduce_5,
  3, 23, :_reduce_6,
  1, 25, :_reduce_7,
  2, 25, :_reduce_8,
  1, 26, :_reduce_9,
  2, 26, :_reduce_10,
  0, 24, :_reduce_11,
  2, 24, :_reduce_12,
  2, 27, :_reduce_13,
  1, 27, :_reduce_14,
  1, 28, :_reduce_15,
  1, 28, :_reduce_16,
  3, 28, :_reduce_17,
  3, 28, :_reduce_18,
  1, 31, :_reduce_none,
  1, 32, :_reduce_20,
  2, 32, :_reduce_21,
  3, 32, :_reduce_22,
  3, 32, :_reduce_23,
  3, 33, :_reduce_24,
  3, 33, :_reduce_25,
  3, 33, :_reduce_26,
  0, 34, :_reduce_27,
  2, 34, :_reduce_28,
  3, 34, :_reduce_29,
  3, 34, :_reduce_30,
  1, 30, :_reduce_31,
  1, 30, :_reduce_32,
  1, 30, :_reduce_33,
  1, 30, :_reduce_34,
  1, 35, :_reduce_35,
  3, 35, :_reduce_36,
  1, 29, :_reduce_37,
  2, 29, :_reduce_38,
  1, 29, :_reduce_39,
  2, 29, :_reduce_40,
  1, 29, :_reduce_41,
  2, 29, :_reduce_42,
  3, 29, :_reduce_43,
  5, 29, :_reduce_44,
  4, 29, :_reduce_45,
  5, 29, :_reduce_46,
  6, 29, :_reduce_47 ]

racc_reduce_n = 48

racc_shift_n = 71

racc_token_table = {
  false => 0,
  :error => 1,
  :PIPE => 2,
  :CARET => 3,
  :DOLLAR => 4,
  :DOT => 5,
  :LP => 6,
  :RP => 7,
  :LB => 8,
  :RB => 9,
  :MINUS => 10,
  :PLUS => 11,
  :COLON => 12,
  :NCNAME => 13,
  :CHAR_TEXT => 14,
  :TEXT => 15,
  :INTEGER => 16,
  :COMMA => 17,
  :STAR => 18,
  :QUESTION => 19,
  :LLB => 20 }

racc_nt_base = 21

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "PIPE",
  "CARET",
  "DOLLAR",
  "DOT",
  "LP",
  "RP",
  "LB",
  "RB",
  "MINUS",
  "PLUS",
  "COLON",
  "NCNAME",
  "CHAR_TEXT",
  "TEXT",
  "INTEGER",
  "COMMA",
  "STAR",
  "QUESTION",
  "LLB",
  "$start",
  "rules",
  "anchored_rule",
  "rule",
  "left_anchor",
  "right_anchor",
  "sequence",
  "atom",
  "sequence_qualifiers",
  "text",
  "atom_expr",
  "char_set_expr",
  "char_set",
  "char_set_text",
  "qname" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'tokens.racc', 5)
  def _reduce_1(val, _values, result)
     result = Fabulator::Grammar::Expr::Token.new; result.add_alternative(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'tokens.racc', 6)
  def _reduce_2(val, _values, result)
     result = val[0]; result.add_alternative(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'tokens.racc', 8)
  def _reduce_3(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'tokens.racc', 9)
  def _reduce_4(val, _values, result)
     result = val[1]; result.anchor_start(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'tokens.racc', 10)
  def _reduce_5(val, _values, result)
     result = val[0]; result.anchor_end(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'tokens.racc', 11)
  def _reduce_6(val, _values, result)
     result = val[1]; result.anchor_start(val[0]); result.anchor_end(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'tokens.racc', 13)
  def _reduce_7(val, _values, result)
     result = '^' 
    result
  end
.,.,

module_eval(<<'.,.,', 'tokens.racc', 14)
  def _reduce_8(val, _values, result)
     result = '^^' 
    result
  end
.,.,

module_eval(<<'.,.,', 'tokens.racc', 16)
  def _reduce_9(val, _values, result)
     result = '$' 
    result
  end
.,.,

module_eval(<<'.,.,', 'tokens.racc', 17)
  def _reduce_10(val, _values, result)
     result = '$$' 
    result
  end
.,.,

module_eval(<<'.,.,', 'tokens.racc', 19)
  def _reduce_11(val, _values, result)
     result = Fabulator::Grammar::Expr::TokenAlternative.new; 
    result
  end
.,.,

module_eval(<<'.,.,', 'tokens.racc', 20)
  def _reduce_12(val, _values, result)
     result = val[0]; result.add_sequence(val[1]); 
    result
  end
.,.,

module_eval(<<'.,.,', 'tokens.racc', 22)
  def _reduce_13(val, _values, result)
     result = Fabulator::Grammar::Expr::Sequence.new(nil, val[0], val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'tokens.racc', 23)
  def _reduce_14(val, _values, result)
     result = Fabulator::Grammar::Expr::Sequence.new(nil, val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'tokens.racc', 25)
  def _reduce_15(val, _values, result)
     result = Fabulator::Grammar::Expr::Text.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'tokens.racc', 26)
  def _reduce_16(val, _values, result)
     result = Fabulator::Grammar::Expr::Any.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'tokens.racc', 27)
  def _reduce_17(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'tokens.racc', 28)
  def _reduce_18(val, _values, result)
     result = val[1] 
    result
  end
.,.,

# reduce 19 omitted

module_eval(<<'.,.,', 'tokens.racc', 33)
  def _reduce_20(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'tokens.racc', 34)
  def _reduce_21(val, _values, result)
     result = Fabulator::Grammar::Expr::CharSet.new; result.universal; result.but_not(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'tokens.racc', 35)
  def _reduce_22(val, _values, result)
     result = val[0].or(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'tokens.racc', 36)
  def _reduce_23(val, _values, result)
     result = val[0].but_not(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'tokens.racc', 38)
  def _reduce_24(val, _values, result)
     result = Fabulator::Grammar::Expr::CharSet.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'tokens.racc', 39)
  def _reduce_25(val, _values, result)
     result = Fabulator::Grammar::Expr::CharClass.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'tokens.racc', 40)
  def _reduce_26(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'tokens.racc', 42)
  def _reduce_27(val, _values, result)
     result = '' 
    result
  end
.,.,

module_eval(<<'.,.,', 'tokens.racc', 43)
  def _reduce_28(val, _values, result)
     result = val[0] + val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'tokens.racc', 44)
  def _reduce_29(val, _values, result)
     result = val[0] + '-' + val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'tokens.racc', 45)
  def _reduce_30(val, _values, result)
     result = val[0] + '+' + val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'tokens.racc', 47)
  def _reduce_31(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'tokens.racc', 48)
  def _reduce_32(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'tokens.racc', 49)
  def _reduce_33(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'tokens.racc', 50)
  def _reduce_34(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'tokens.racc', 52)
  def _reduce_35(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'tokens.racc', 53)
  def _reduce_36(val, _values, result)
     result = val[0] + ':' + val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'tokens.racc', 55)
  def _reduce_37(val, _values, result)
     result = [ :zero_or_more ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'tokens.racc', 56)
  def _reduce_38(val, _values, result)
     result = [ :zero_or_more, :min ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'tokens.racc', 57)
  def _reduce_39(val, _values, result)
     result = [ :one_or_more ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'tokens.racc', 58)
  def _reduce_40(val, _values, result)
     result = [ :one_or_more, :min ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'tokens.racc', 59)
  def _reduce_41(val, _values, result)
     result = [ :zero_or_one ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'tokens.racc', 60)
  def _reduce_42(val, _values, result)
     result = [ :zero_or_one, :min ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'tokens.racc', 61)
  def _reduce_43(val, _values, result)
     result = [ :exact, val[1].to_i ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'tokens.racc', 62)
  def _reduce_44(val, _values, result)
     result = [ :range, val[1].to_i, val[3].to_i ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'tokens.racc', 63)
  def _reduce_45(val, _values, result)
     result = [ :range, val[1], '' ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'tokens.racc', 64)
  def _reduce_46(val, _values, result)
     result = [ :min, :range, val[1], '' ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'tokens.racc', 65)
  def _reduce_47(val, _values, result)
     result = [ :min, :range, val[1].to_i, val[3].to_i ] 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

    end   # class TokenParser
    end   # module Grammar
  end   # module Fabulator
